"""add email verification field

Revision ID: bd025ef8f221
Revises: 63bffea6dbe9
Create Date: 2025-10-24 00:11:33.080123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd025ef8f221'
down_revision = '63bffea6dbe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('verification_sent_at')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('verification_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('verification_sent_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
